int ROT = 13;
int GRUEN = 12;
int BLAU = 11;
void setup(){
pinMode(ROT, OUTPUT);
pinMode(GRUEN, OUTPUT);
pinMode(BLAU, OUTPUT);
}
void loop(){
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, LOW);
digitalWrite(BLAU, LOW);
delay(5000);
digitalWrite(ROT, LOW);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, LOW);
delay(50000);
digitalWrite(ROT, LOW);
digitalWrite(GRUEN, LOW);
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, LOW);
delay(50000);
digitalWrite(ROT, LOW);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, LOW);
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, LOW);
digitalWrite(BLAU, LOW);
delay(5000);
digitalWrite(ROT, LOW);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, LOW);
delay(50000);
digitalWrite(ROT, LOW);
digitalWrite(GRUEN, LOW);
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, LOW);
delay(50000);
digitalWrite(ROT, LOW);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, LOW);
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, LOW);
digitalWrite(BLAU, LOW);
delay(5000);
digitalWrite(ROT, LOW);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, LOW);
delay(50000);
digitalWrite(ROT, LOW);
digitalWrite(GRUEN, LOW);
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, LOW);
delay(50000);
digitalWrite(ROT, LOW);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, LOW);
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, LOW);
digitalWrite(BLAU, LOW);
delay(5000);
digitalWrite(ROT, LOW);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, LOW);
delay(50000);
digitalWrite(ROT, LOW);
digitalWrite(GRUEN, LOW);
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, LOW);
delay(50000);
digitalWrite(ROT, LOW);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN,LOW );
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, LOW);
digitalWrite(BLAU, LOW);
delay(5000);
digitalWrite(ROT, LOW);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, LOW);
delay(50000);
digitalWrite(ROT, LOW);
digitalWrite(GRUEN, LOW);
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, LOW);
delay(50000);
digitalWrite(ROT, LOW);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, HIGH);
digitalWrite(BLAU, HIGH);
delay(50000);
digitalWrite(ROT, HIGH);
digitalWrite(GRUEN, LOW);
digitalWrite(BLAU, HIGH);
delay(50000);

}
